version: "3"
services:
  redis:
    image: redis
    container_name: redis
    networks:
      - mi_red

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - mi_red

networks:
  mi_red:
