apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miapp
  template:
    metadata:
      labels:
        app: miapp
    spec:
      containers:
        - name: miapp
          image: miacrdemougrm.azurecr.io/miapp:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: miapp-service
spec:
  type: LoadBalancer
  selector:
    app: miapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
