trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r Devops/pyhton/01/requirements.txt
    python Devops/pyhton/01/app.py
  displayName: 'Run Hola Mundo App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'CONEXION'
    appType: 'webAppLinux'
    appName: 'pyhon01'
    package: $(Build.ArtifactStagingDirectory)/**/*.zip